version: "3.6"

services:
  peripheral-manager-network:
    build: .
    restart: on-failure
    network_mode: host
    volumes:
      - nuvlabox-db:/srv/nuvlaedge/shared
    labels:
      - nuvlaedge.component=True
      - nuvlaedge.deployment=production
